cargo: auto-upgrade dependencies
Note that `built` is kept on `0.7.2` and not latest `0.7.4` because of
error [1].

[1]

error[E0658]: use of unstable library feature 'io_error_other'
  --> /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/built-0.7.3/src/dependencies.rs:24:16
   |
24 |         .ok_or(io::Error::other("Cargo.lock not found"))
   |                ^^^^^^^^^^^^^^^^
   |
   = note: see issue #91946 <https://github.com/rust-lang/rust/issues/91946> for more information