cargo: bump msrv to 1.78 and set package.rust-version
This is due to Cargo lockfile format changing to v4.

On rust 1.74 build fails with the following error:

error: failed to parse lock file at: /home/runner/work/ch4/ch4/Cargo.lock

Caused by:
  lock file version `4` was found, but this version of Cargo does not understand this lock file, perhaps Cargo needs to be updated?